image: cr.d.xiaomi.net/sparsedl/devel:latest

stages:
  - linting
  - build

pylint:
  stage: linting
  script:
    - yapf --version
    - yapf --style=pep8 -r -d autosparsedl/ examples/ test/

unittest-python:
  stage: build
  script:
    - pushd test/
    - python3 -m unittest -v *_test.py
    - popd

