experiment:
  context:
    name: avglabel-v2

  main_loop:
    warmup: 
      student_nums: 0
    nums: 100
    student_nums: 1

  student:
    dataloader:
      name: cifar10 # default cifar10
      epochs: 50
    model:
      name: dnn # default dnn
    loss:
      name: SparseCategoricalCrossentropy
    metrics: 
      name: SparseCategoricalAccuracy
    optimizer:
      name: Adam # default SGD
      learning_rate: 0.0001 # default 0.01
    train_loop:
        valid:
          valid_gap: 100

  supervisor:
    dataloader:
      name: dnn_weights
      replay_window: 30
      batch_size: 32
      epochs: 10
    model:
      name: dnn # default dnn
    optimizer:
      name: sgd
      learning_rate: 0.01
    loss:
      name: mean_absolute_error #mean_absolute_error
    train_loop:
        valid:
          valid_gap: 100 