experiment:
  context:
    name: fda-act10-nQ
    devices: [0,1,2,3]
    multi-p: True

  main_loop:
    warmup: 
      student_nums: 0
      supervisor_trains: 10
    nums: 1000
    student_nums: 4

  student:
    dataloader:
      name: cifar10 # default cifar10
      batch_size: 512
      epochs: 300
      da: True
      task: RL
    model:
      name: dnn # default dnn
      units: [128,64,32,10] # default 128,64,64,32
      activations: [relu,relu,relu,softmax] # default relu
    loss:
      name: CategoricalCrossentropy
    metrics: 
      name: categorical_accuracy
    optimizer:
      name: sgd # default SGD
      learning_rate: 0.1 # default 0.01
    train_loop:
        train:
          lr_decay: False
          action: fix
          policy: greedy
        valid:
          weight_space:
            format: sum_reduce
          valid_gap: 30

  supervisor:
    dataloader:
      name: dnn_sr_RL
      replay_window: 64
      batch_size: 32
      epochs: 100
    model:
      name: dnn # default dnn
      units: [128,64,32,1] # default 128,64,64,32
      embedding: True
      activations: [relu,relu,relu,relu] # default relu
    optimizer:
      name: sgd
      learning_rate: 0.01
    loss:
      name: MeanAbsoluteError #MeanAbsoluteError 
    train_loop:
        valid:
          valid_gap: 10000 