experiment:
  context:
    name: multi-p-v3
    multi-p: False

  main_loop:
    warmup: 
      student_nums: 1
      supervisor_trains: 1
    nums: 0
    student_nums: 1

  student:
    dataloader:
      name: cifar10 # default cifar10
      batch_size: 128
      epochs: 150
    model:
      name: dnn # default dnn
    loss:
      name: SparseCategoricalCrossentropy
    metrics: 
      name: SparseCategoricalAccuracy
    optimizer:
      name: sgd # default SGD
      learning_rate: 0.1 # default 0.01
    train_loop:
        valid:
          valid_gap: 1000

  supervisor:
    dataloader:
      name: dnn_weights
      replay_window: 30
      batch_size: 128
      epochs: 10
    model:
      name: dnn # default dnn
    optimizer:
      name: sgd
      learning_rate: 0.01
    loss:
      name: MeanAbsoluteError #MeanAbsoluteError 
    train_loop:
        valid:
          valid_gap: 100 