experiment:
  context:
    name: neu-v1
    multi-p: True

  main_loop:
    warmup: 
      student_nums: 5
      supervisor_trains: 3
    nums: 10
    student_nums: 5

  student:
    dataloader:
      name: cifar10 # default cifar10
      epochs: 150
    model:
      name: dnn # default dnn
    loss:
      name: SparseCategoricalCrossentropy
    metrics: 
      name: SparseCategoricalAccuracy
    optimizer:
      name: Adam # default SGD
      learning_rate: 0.0001 # default 0.01
    train_loop:
        valid:
          valid_gap: 100

  supervisor:
    dataloader:
      name: dnn_weights
      replay_window: 20
      batch_size: 64
      epochs: 50
    model:
      name: dnn # default dnn
      units: 64,32,16,10
      activations: relu,relu,relu,relu,
      use_neu: True
    optimizer:
      name: sgd
      learning_rate: 0.0001
    loss:
      name: MeanAbsoluteError #MeanAbsoluteError 
    train_loop:
        valid:
          valid_gap: 100 