experiment:

  main_loop:
    warmup: 
      student_nums: 1
    nums: 0
    student_nums: 0

  student:
    dataloader:
      name: cifar10 # default cifar10
    model:
      name: dnn # default dnn
    loss:
      name: SparseCategoricalCrossentropy
    metric: 
      name: accuracy
    optimizer:
      name: SGD # default SGD
      learning_rate: 0.01 # default 0.01
    train_loop:
        max_training_epochs: 10 # default 10

  supervisor:
    dataloader:
      name: dnn_weights
    model:
      name: dnn # default dnn
    optimizer:
      name: SGD
      learning_rate: 0.01
    loss:
      name: mean_squared_error
    train_loop:
        max_training_epochs: 10 