experiment:
  context:
    name: reval
    devices: 0
    log_path: ./log

  main_loop:
    warmup: 
      student_nums: 100
      supervisor_trains: 0
    nums: 0
    student_nums: 0

  student:
    dataloader:
      name: cifar10 # default cifar10
      epochs: 10
      batch_size: 128
      da: True
    model:
      name: dnn # default dnn
      units: [128,64,32,10]
      activations: [relu,relu,relu,softmax]
    loss:
      name: CategoricalCrossentropy
    metrics: 
      name: CategoricalAccuracy
    optimizer:
      name: sgd # default SGD
      learning_rate: 0.1 # default 0.01
    train_loop:
        train:
          lr_decay: True
        valid:
          valid_gap: 100 
          weight_space: sum_reduce
          online_update: False
          visual: False

  supervisor:
    dataloader:
      name: dnn_weights
      batch_size: 32
      epochs: 10
    model:
      name: dnn # default dnn
      units: [128,64,32,1]
      activations: [relu,relu,relu,relu]
    optimizer:
      name: SGD
      learning_rate: 0.001
    loss:
      name: mean_squared_error
    train_loop:
        valid:
          valid_gap: 100 