experiment:

  main_loop:
    warmup: 
      student_nums: 0
    nums: 30
    student_nums: 0

  student:
    dataloader:
      name: cifar10 # default cifar10
      epochs: 10
    model:
      name: dnn # default dnn
    loss:
      name: SparseCategoricalCrossentropy
    metrics: 
      name: SparseCategoricalAccuracy
    optimizer:
      name: Adam # default SGD
      learning_rate: 0.001 # default 0.01
    train_loop:
        valid:
          valid_gap: 100 

  supervisor:
    dataloader:
      name: dnn_weights
      epochs: 1
    model:
      name: dnn # default dnn
    optimizer:
      name: Adam
      learning_rate: 0.001
    loss:
      name: mean_squared_error
    train_loop:
        valid:
          valid_gap: 100 