experiment:

  context:
    experiment_type: train_supervisor
    log_path: ./

  surrogate_trainer:
    dataloader:
      name: dnn_weights
      surrogaet_dataset_path: ./dataset/weights_pool/dnn # as default
      batch_size: 32
    model:
      name: dnn # default dnn
      deep_dims: 128,64,64,32
      activation_for_each: relu,sigmoid,sigmoid,relu
      restore_model:
        version: latest # or best, default None
    optimizer:
      name: SGD
      learning_rate: 0.01
    loss:
      name: mean_squared_error
      metric: mean_squared_logarithmic_error
    train_loop_control:
      train:
        max_training_epochs: 10 # default inf
