experiment:

  context:
    name: "001"
    experiment_type: train_target_model
    log_path: ./

  target_trainer:
    dataloader:
      name: cifar10 # default cifar10
      trainer_dataset_path: ~/.keras/dataset/cifar10
      batch_size: 256
    model:
      name: dnn # default dnn
      deep_dims: 128,64,64,10 # default 128,64,64,32
      activations_for_all: relu,relu,relu,softmax # default relu
      restore_model:
        restore_from: latest # or best
    loss:
      name: SparseCategoricalCrossentropy
      metric: accuracy
    optimizer:
      name: SGD # default SGD
      learning_rate: 0.01 # default 0.01
      scheduler: None # default None
    train_loop_control:
      train:
        check_should_train: True
        max_training_steps: 1000 # default 10000
        max_training_epochs: 10 # default 10
      valid:
        check_should_valid: True # default False for no validation step
        valid_gap: 1000 # default 1000 training steps
        valid_steps: 100 # default valid for 100 steps
        analyse: False
        save_model:
          save_in: "001"
          save_after_step: 1000 # save latest and best model per 1000 steps
      test:
        check_should_test: True # default False for no test step