experiment:

  context:
    name: "001"
    experiment_type: train_target_model
    log_path: ./

  target_trainer:
    name: ImageNetTrainer
    dataloader:
      name: imagenet # default cifar10
      datapath: /home/work/dataset/ILSVRC2012/downloads/manual/train_records
      batch_size: 256
      sample_of_curves: 250
    model:
      name: resnet50 # default dnn
    loss:
      name: SparseCategoricalCrossentropy
      metric: accuracy
    optimizer:
      name: SGD # default SGD
      learning_rate: 0.01 # default 0.01
    train_loop_control:
      train:
        check_should_train: True
        max_training_steps: 1000 # default 10000
        max_training_epochs: 10 # default 10
      valid:
        check_should_valid: True # default False for no validation step
        valid_gap: 1000 # default 1000 training steps
        valid_steps: 100 # default valid for 100 steps
        save_model:
          save_in: "001"
          save_after_step: 1000 # save latest and best model per 1000 steps
      test:
        check_should_test: True # default False for no test step